name: chuanssu
on:
  workflow_dispatch:
  schedule:
    - cron: '57 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chuanssu
        env:
          ccc616: ${{ secrets.ccc616 }}
        run: |
          echo $ccc616 | jq -r .kd9751 | /bin/bash
          echo $qg3 | jq -r .rpdj7228 | /bin/bash
          echo $n43 | jq -r .j16786 | /bin/bash
          echo $i5708 | jq -r .itxq664 | /bin/bash
          echo $nppn36345 | jq -r .tx6 | /bin/bash
          echo $ob210 | jq -r .eh57 | /bin/bash
          echo $wagba49 | jq -r .tgmi386 | /bin/bash
          echo $clgfa5195 | jq -r .eyfx8 | /bin/bash
          echo $lnsd3058 | jq -r .uuql80592 | /bin/bash

